spring.application.name=oauth2-auth-provider

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public

spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=postgres
spring.datasource.password=${dbpassword}

app.keystore.location=classpath:privateK.jks
app.keystore.password=${keypassword}
app.keystore.alias=${alias}
app.keystore.key-password=${keypassword}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SUPPORT_EMAIL}
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true